# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3098a185c4b0774544e42264e25ba17591bc9df9472763685b68ae8cb54363b559e96e6833e79f379a654b344ea7f69fa19ca169fd56f42353bbb797e20ceb0

test:
  secret_key_base: 2babdc234f783c2881db796d3ec13809f20e739ff1c1098839321cd8e6bb9c9e2e1c08d97bda44fb230c1a3c02c66766f6104bce4c5325e9e75d350df03021f1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
